AllCops:
  Exclude:
    - vendor/**/*
    - bin/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: true

ClassLength:
  Enabled: false

FileName:
  Enabled: false

Encoding:
  Enabled: false
